CREATE DATABASE DBlabcad;
USE DBlabcad;
CREATE TABLE TBreserva_lab (
    resID INT PRIMARY KEY AUTO_INCREMENT NOT NULL, /*UNIQUE*/
    resNOME_CURSO_DISCIPLINA VARCHAR(110) NOT NULL,
    resNOME_DEPARTAMENTO VARCHAR(75) NOT NULL,
    resNOME_RESP_CURSO_DISCIPLINA VARCHAR(150) NOT NULL,
    resNOME_PROF_CURSO_DISCIPLINA VARCHAR(150) NOT NULL,
    resDATA_RESERVA VARCHAR(10) NOT NULL, /*Horario*/
    resHORA_RESERVA VARCHAR(5) NOT NULL,
    resQTD_ALUNOS SMALLINT NOT NULL,
    resNOME_PROGRAMAS VARCHAR(250) NOT NULL,
    resEMAIL_RESP_RESERVA VARCHAR(150) NOT NULL,
    resCIENTE BOOLEAN NOT NULL,
    resMSG_OBS VARCHAR(250) NULL
);
select * from `dblabcad`.tbreserva_lab;
INSERT INTO TBreserva_lab( 
/*resID,*/ resNOME_CURSO_DISCIPLINA, resNOME_DEPARTAMENTO, 
resNOME_RESP_CURSO_DISCIPLINA, resNOME_PROF_CURSO_DISCIPLINA, 
resDATA_RESERVA, resHORA_RESERVA, resQTD_ALUNOS, resNOME_PROGRAMAS, 
resEMAIL_RESP_RESERVA, resCIENTE, resMSG_OBS) VALUES(
        'DCC','Edificios',
        'Aux', 'ProfAux',
        '28-01-2025', '16-00',
        14, 
        '$AutoCAD_2025, $SketchUP, $Revit_2025, $Office_2019, $Others',
        'gmail@com', true, 'O123');
ALTER TABLE TBRESERVA_LAB MODIFY COLUMN resDATA_RESERVA DATETIME NOT NULL;
ALTER TABLE TBRESERVA_LAB MODIFY COLUMN resDATA_PEDIDO DATETIME NOT NULL;
ALTER TABLE TBRESERVA_LAB ADD UNIQUE (resID);
INSERT INTO TBRESERVA_LAB (resDATA_PEDIDO)VALUES(LOCALTIME());
/*
CREATE TABLE TBfale_conosco(
	falID INT PRIMARY KEY AUTO_INCREMENT,
	falNOME VARCHAR(150) NOT NULL,
    falEMAIL VARCHAR(150) NOT NULL,
    falMSG_OBS VARCHAR(250) NOT NULL
);
ALTER TABLE ;
SELECT;

*/
